[default_session]
startup_command = "nvim -c ':lua Snacks.picker.files()'"
[[session]]
name = "Notes 📝"
path = "~/Documents/notes/"
[[session]]
name = "dotfiles 📂"
path = "~/dotfiles"
[[session]]
name = "Olympic"
path = "~"
startup_command = "~/.config/sesh/scripts/olympic"
