[default_session]
startup_command = "nvim -c ':Telescope find_files'"
[[session]]
name = "Downloads 📥"
path = "~/Downloads"
[[session]]
name = "dotfiles 📂"
path = "~/dotfiles"
[[session]]
name = "spoorweb 🚂"
path = "~/Documents/prorail/Spoorweb/"
[[session]]
name = "Olympic"
path = "~"
startup_command = "~/.config/sesh/scripts/olympic"
