return {
	-- {
	-- 	"hrsh7th/nvim-cmp",
	-- 	dependencies = {
	-- 		"hrsh7th/cmp-nvim-lsp",
	-- 		"hrsh7th/cmp-buffer",
	-- 		"hrsh7th/cmp-path",
	-- 		"hrsh7th/cmp-cmdline",
	-- 		"L3MON4D3/LuaSnip",
	-- 		"saadparwaiz1/cmp_luasnip",
	-- 	},
	-- 	config = function()
	-- 		local cmp = require("cmp")
	-- 		cmp.setup({
	-- 			snippet = {
	-- 				expand = function(args)
	-- 					require("luasnip").lsp_expand(args.body)
	-- 				end,
	-- 			},
	-- 			window = {
	-- 				completion = cmp.config.window.bordered({
	-- 					col_offset = 20,
	-- 				}),
	-- 				documentation = cmp.config.window.bordered(),
	-- 			},
	-- 			formatting = {
	-- 				fields = { "abbr", "kind", "menu" },
	-- 				format = function(entry, vim_item)
	-- 					return vim_item
	-- 				end,
	-- 			},
	-- 			mapping = cmp.mapping.preset.insert({
	-- 				["<C-b>"] = cmp.mapping.scroll_docs(-4),
	-- 				["<C-f>"] = cmp.mapping.scroll_docs(4),
	-- 				["<C-Space>"] = cmp.mapping.complete(), -- Manual trigger
	-- 				["<C-e>"] = cmp.mapping.abort(),
	-- 				["<CR>"] = cmp.mapping.confirm({ select = true }),
	-- 				["<Tab>"] = cmp.mapping.select_next_item(),
	-- 				["<S-Tab>"] = cmp.mapping.select_prev_item(),
	-- 			}),
	-- 			sources = cmp.config.sources({
	-- 				{ name = "codeium" },
	-- 				{ name = "nvim_lsp" },
	-- 				{ name = "luasnip" },
	-- 				{ name = "buffer" },
	-- 				{ name = "path" },
	-- 			}),
	-- 			-- Disable automatic completion
	-- 			completion = {
	-- 				autocomplete = false, -- Disable auto-popup
	-- 			},
	-- 			experimental = {
	-- 				ghost_text = true, -- Optional: show ghost text
	-- 			},
	-- 		})
	-- 	end,
	-- },
}
