binds {
    workspace_back_and_forth = true
  }

env = EDITOR,nvim

input {
    kb_options=ctrl:nocaps
    # force_no_accel = true
    accel_profile = flat
}

misc {
    vrr = 1
  }
gesture = 3, horizontal, workspace

unbind = SUPER, M
bind = SUPER, M, exec, pypr-client menu "monitor menu"
bind = SUPER SHIFT, M, exec, pypr-client menu
bind = SUPER, C, exec, pypr-client toggle ferdium
unbind = SUPER, T
bind = SUPER, T, exec, pypr-client toggle term

env = HYPRCURSOR_THEME,rose-pine-hyprcursor

unbind = SUPER, D
# Move focus with SUPER + WASD
bindd = SUPER, A, Move focus left, movefocus, l
bindd = SUPER, D, Move focus right, movefocus, r
bindd = SUPER, W, Move focus up, movefocus, u
bindd = SUPER, S, Move focus down, movefocus, d

# Swap active window with the one next to it with SUPER + SHIFT + WASD
bindd = SUPER SHIFT, A, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, D, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, W, Swap window up, swapwindow, u
bindd = SUPER SHIFT, S, Swap window down, swapwindow, d

