[pyprland]
plugins = [
    "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -e btop"
class = "kitty-dropterm"
size = "75% 60%"
max_size = "1920px 100%"
margin = 50

[scratchpads.ferdium]
animation = "fromBottom"
command = "ferdium"
class = "ferdium"
size = "75% 90%"
max_size = "1920px 100%"
margin = 50
