-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Autostart Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/defaults.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.defaults")

-- Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

-- exec-once = uwsm app -- /usr/lib/polkit-kde-authentication-agent-1
-- exec-once = systemctl --user enable --now hyprpolkitagent.service
-- exec-once = uwsm app -- 1password --silent
-- exec-once = uwsm app -- hyprfloat

hl.on("hyprland.start", function()
	hl.exec_cmd("uwsm app -- waypaper --restore")
	hl.exec_cmd("uwsm app -- waybar")
	hl.exec_cmd("uwsm app -- swayosd-server")
	hl.exec_cmd("uwsm app -- elephant")
	hl.exec_cmd("walker --gapplication-service")
	hl.exec_cmd("uwsm app -- mako")
	hl.exec_cmd("uwsm app -- /usr/bin/pypr")
	hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
	hl.exec_cmd("uwsm app -- hyprdynamicmonitors run  --disable-power-events --enable-lid-events")
	hl.exec_cmd("uwsm app -- " .. idlehandler)
	hl.exec_cmd("uwsm app -- wl-paste --type text --watch cliphist store")
	hl.exec_cmd("uwsm app -- wl-paste --type image --watch cliphist store")
	hl.exec_cmd("uwsm app -- udiskie")
	hl.exec_cmd("uwsm app -- pass-cli ssh-agent start")
end)
