-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Decorations Configuration                ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

require("config.colors")

hl.config({
	decoration = {
		active_opacity = 1,
		rounding = 4,
		blur = {
			size = 15,
			passes = 2,
			xray = true,
		},
		shadow = {
			enabled = false,
		},
	},
})
