-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Enviroment Configuration                 ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("HYPRCURSOR_SIZE", "24")
-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("XCURSOR_SIZE", "24")
-- Note: 'envd' (systemd/D-Bus-propagated) becomes a regular hl.env in Lua. If you relied on D-Bus propagation, set the variable via systemctl --user import-environment as a separate step.
hl.env("QT_CURSOR_SIZE", "24")
hl.env("EDITOR", "nvim")
hl.env("HYPRCURSOR_THEME", "rose-pine-hyprcursor")

-- Force all apps to use Wayland
hl.env("GDK_BACKEND", "wayland,x11,*")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("OZONE_PLATFORM", "wayland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GDK_SCALE", "1")
hl.env("GFK_DPI_SCALE", "1")

-- Allow better support for screen sharing (Google Meet, Discord, etc)
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.config({
	xwayland = {
		force_zero_scaling = true,
	},
})
