-- Generated with hyprdynamicmonitors freeze.
-- This is a template that you can edit, it is just a starter that pulled your current monitor setup,
-- adjust as needed.
-- You can use templates here etc, see https://github.com/fiffeek/hyprdynamicmonitors/blob/main/examples/basic/hyprconfigs/template.go.tmpl.
-- Monitors are given arbitrary tags (the "monitor" prefix and the ID coming from hyprland).
-- If you are using tui to edit, leave this at the end of your file (the last monitor config applies)
-- and leave the markers.
-- <<<<< TUI AUTO START
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:BOE NE135A1M-NY1",
    mode = "2880x1920@120.00000",
    position = "0x0",
    scale = "1.5",
    transform = 0,
    vrr = 1,
})

-- <<<<< TUI AUTO END

hl.workspace_rule({
    workspace = "1",
    monitor = "desc:BOE NE135A1M-NY1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "7",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "desc:BOE NE135A1M-NY1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "desc:BOE NE135A1M-NY1",
})

