-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Variables Configuration                  ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/config/colors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("config.colors")
local colors = require("config.colors")

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
	general = {
		gaps_in = 3,
		gaps_out = 5,
		border_size = 3,
		col = {
			active_border = colors.cachylgreen,
			inactive_border = colors.cachymblue,
		},
		layout = "dwindle",
		snap = {
			enabled = true,
		},
	},
	-- removed old gestures {} block — Hyprland 0.39+ uses gesture = … lines
	-- https://wiki.hyprland.org/Configuring/Variables/#group
	group = {
		col = {
			border_active = colors.cachydgreen,
			border_inactive = colors.cachylgreen,
			border_locked_active = colors.cachymgreen,
			border_locked_inactive = colors.cachydblue,
		},
		-- https://wiki.hyprland.org/Configuring/Variables/#groupbar
		groupbar = {
			font_family = '"Fira Sans"',
			text_color = colors.cachydblue,
			col = {
				active = colors.cachydgreen,
				inactive = colors.cachylgreen,
				locked_active = colors.cachymgreen,
				locked_inactive = colors.cachydblue,
			},
		},
	},
	-- https://wiki.hyprland.org/Configuring/Variables/#misc
	misc = {
		font_family = '"Fira Sans"',
		splash_font_family = '"Fira Sans"',
		disable_hyprland_logo = true,
		col = {
			splash = colors.cachylgreen,
		},
		background_color = colors.cachydblue,
		enable_swallow = true,
		swallow_regex = "^(nautilus|nemo|thunar|btrfs-assistant.)$",
		focus_on_activate = true,
		vrr = 2,
		-- vfr = true
	},
	-- https://wiki.hyprland.org/Configuring/Variables/#render
	render = {
		direct_scanout = true,
	},
	-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
	dwindle = {
		special_scale_factor = 0.8,
		-- pseudotile = true
		preserve_split = true,
	},
	-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
	master = {
		new_status = "master",
		special_scale_factor = 0.8,
	},
})
