-- ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
-- ┃                    Windowrules Configuration                ┃
-- ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

-- Windows Rules https://wiki.hyprland.org/Configuring/Window-Rules/ #
-- Define terminal tag to style them uniformly
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
	match = {
		class = "(Alacritty|kitty|com.mitchellh.ghostty)",
	},
	tag = "+terminal",
})

-- Float Necessary Windows
hl.window_rule({
	match = {
		class = "^(org.pulseaudio.pavucontrol)",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^()$",
		title = "^(Picture in picture)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^()$",
		title = "^(Save File)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^()$",
		title = "^(Open File)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(LibreWolf)$",
		title = "^(Picture-in-Picture)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(blueman-manager)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(CachyOSHello)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(zenity)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^()$",
		title = "^(Steam - Self Updater)$",
	},
	float = true,
})

hl.window_rule({
	match = {
		class = "^(Ferdium)$",
	},
	float = true,
})

-- Increase the opacity
hl.window_rule({
	match = {
		class = "^(thunar|nemo)$",
	},
	opacity = 0.92,
})

hl.window_rule({
	match = {
		class = "^(discord|armcord|webcord)$",
	},
	opacity = 0.96,
})

hl.window_rule({
	match = {
		title = "^(QQ|Telegram)$",
	},
	opacity = 0.95,
})

hl.window_rule({
	match = {
		title = "^(NetEase Cloud Music Gtk4)$",
	},
	opacity = 0.95,
})

-- General window rules
-- windowrule = float on, size 960 540, move ((monitor_w*0.25)-), match:title ^(Picture-in-Picture)$
-- windowrule = float on, move ((monitor_w*0.25)-), size 960 540, match:title ^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$
hl.window_rule({
	match = {
		title = "^(danmufloat)$",
	},
	pin = true,
})

hl.window_rule({
	match = {
		title = "^(danmufloat|termfloat)$",
	},
	rounding = 5,
})

hl.window_rule({
	match = {
		class = "^(kitty|Alacritty)$",
	},
	animation = "slide right",
})

hl.window_rule({
	match = {
		class = "^(org.mozilla.firefox)$",
	},
	-- TODO: manual review — unmapped window rule action: "no_blur on"
})

-- Decorations related to floating windows on workspaces 1 to 10
hl.window_rule({
	match = {
		float = 1,
		workspace = "w[fv1-10]",
	},
	rounding = 8,
})

-- Decorations related to tiling windows on workspaces 1 to 10
hl.window_rule({
	match = {
		float = 0,
		workspace = "f[1-10]",
	},
	rounding = 4,
})

-- Windows Rules End #

-- Floating windows
hl.window_rule({
	match = {
		tag = "floating-window",
	},
	float = true,
	center = true,
	size = "1000 900",
})

hl.window_rule({
	match = {
		class = "(Bluetui|Btop|Wifi|blueberry.py|Impala|Wiremix|org.gnome.NautilusPreviewer|com.gabm.satty|Omarchy|About|TUI.float)",
	},
	tag = "+floating-window",
})

hl.window_rule({
	match = {
		class = "(xdg-desktop-portal-gtk|sublime_text|DesktopEditors|org.gnome.Nautilus)",
		title = "^(Open.*Files?|Open [F|f]older.*|Save.*Files?|Save.*As|Save|All Files)",
	},
	tag = "+floating-window",
})

hl.window_rule({
	match = {
		class = "org.gnome.Calculator",
	},
	float = true,
})

--1password
hl.window_rule({
	match = {
		class = "^(1Password|Proton Pass)$",
	},
})

-- Remove 1px border around hyprshot screenshots
hl.layer_rule({
	match = { namespace = "match:namespace selection" },
})

-- Float LocalSend and fzf file picker
hl.window_rule({
	match = {
		class = "(Share|localsend)",
	},
	float = true,
	center = true,
})

-- Float Steam
hl.window_rule({
	match = {
		class = "steam",
	},
	float = true,
	opacity = "1 1",
})

hl.window_rule({
	match = {
		class = "steam",
		title = "Steam",
	},
	center = true,
	size = "1100 700",
})

hl.window_rule({
	match = {
		class = "steam",
		title = "Friends List",
	},
	size = "460 800",
})

-- No transparency on media windows
hl.window_rule({
	match = {
		class = "^(zoom|vlc|mpv|org.kde.kdenlive|com.obsproject.Studio|com.github.PintaProject.Pinta|imv|org.gnome.NautilusPreviewer)$",
	},
	opacity = "1 1",
})

-- Application-specific animation
hl.layer_rule({
	match = { namespace = "match:namespace walker" },
})

hl.workspace_rule({
	workspace = "w[tv1-10]",
	gaps_out = 5,
	gaps_in = 3,
})

hl.workspace_rule({
	workspace = "f[1]",
	gaps_out = 5,
	gaps_in = 3,
})

-- Workspaces Rules End #

-- Layers Rules #
hl.layer_rule({
	match = { namespace = "match:namespace logout_dialog" },
	animation = "slide top",
})

-- layerrule = animation popin 50%, waybar
hl.layer_rule({
	match = { namespace = "match:namespace waybar" },
	animation = "slide down",
})

hl.layer_rule({
	match = { namespace = "match:namespace wallpaper" },
	animation = "fade 50%",
})

-- Layers Rules End #

hl.window_rule({
	match = {
		title = "^(1Password|Proton Pass)",
	},
	float = true,
	size = "(monitor_w*0.7) (monitor_h*0.7)",
	center = true,
})
