# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = uwsm app -- waypaper --restore
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- elephant
exec-once = walker --gapplication-service
exec-once = uwsm app -- mako
exec-once = uwsm app -- /usr/bin/pypr
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once = uwsm app -- /usr/lib/polkit-kde-authentication-agent-1
# exec-once = systemctl --user enable --now hyprpolkitagent.service
# exec-once = uwsm app -- 1password --silent
exec-once = uwsm app -- hyprdynamicmonitors run  --disable-power-events --enable-lid-events
# exec-once = uwsm app -- hyprfloat
exec-once = uwsm app -- $idlehandler
exec-once = uwsm app -- wl-paste --type text --watch cliphist store # Stores only text data
exec-once = uwsm app -- wl-paste --type image --watch cliphist store # Stores only image data
exec-once = uwsm app -- udiskie
exec-once = uwsm app -- pass-cli ssh-agent start
