# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Autostart Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

source = ~/.config/hypr/config/defaults.conf

# Autostart wiki https://wiki.hyprland.org/Configuring/Keywords/#executing

exec-once = uwsm app -- waypaper --restore
exec-once = uwsm app -- waybar
exec-once = uwsm app -- swayosd-server
exec-once = systemctl --user start elephant
exec-once = uwsm app -- walker --gapplication-service
# exec-once = uwsm app -- fcitx5 -d
exec-once = uwsm app -- mako
exec-once = uwsm app -- /usr/bin/pypr
# exec-once = uwsm app -- bash -c "mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown"
exec-once = systemctl --user enable --now hyprpolkitagent.service
exec-once = uwsm app -- 1password --silent
exec-once = uwsm app -- hyprdynamicmonitors run  --disable-power-events --enable-lid-events
exec-once = uwsm app -- hyprfloat

# ## Slow app launch fix
# exec-once = systemctl --user import-environment
# exec-once = uwsm app -- hash dbus-update-activation-environment 2>/dev/null
# exec-once = uwsm app -- dbus-update-activation-environment --systemd

# ## Idle configuration
exec-once = uwsm app -- $idlehandler
