# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = nautilus
$applauncher = walker
$terminal = kitty
$idlehandler = hypridle

# Screenshots
$shot-region = grimblast copy area & notify-send "Area screenshot taken"
$shot-window = grimblast copy active & notify-send "Windows screenshot taken"
$shot-screen = grimblast copy output & notify-send "Screenshot taken"

#SwayOSD as osdclient
$osdclient = swayosd-client --monitor "$(hyprctl monitors -j | jq -r '.[] | select(.focused == true).name')"
