# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    kb_options = ctrl:nocaps
    accel_profile = flat
    repeat_rate = 40
    repeat_delay = 600

    touchpad {
        clickfinger_behavior = true
        natural_scroll = true
        scroll_factor = 0.4
    }
}

cursor {
    inactive_timeout = 10
}
#windowrule = scrolltouchpad 1.5, tag:terminal
# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Gestures                                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# 4-finger horizontal swipe to switch workspaces
gesture = 3, horizontal, workspace

# # 3-finger swipe down closes active window
# gesture = 3, down, close
#
# # 3-finger swipe up toggles fullscreen
# gesture = 3, up, fullscreen
#
# # 3-finger swipe left toggles float/tile
# gesture = 3, left, float
